//1 задача
console.error("1 Задание")
console.log("JavaScript")
console.log("Flutter")
console.log("TypeScript")
//2 задача
console.error("2 Задание")
console.log("Значение 1 выражения")
console.log(42 / 7)
console.log("Значение 2 выражения")
console.log(2** 4 )
console.log("Значение 3 выражения")
console.log(100 % 4)
console.log("Сумма всех 3х выражений")
console.log(6+16+0)

//2 задача (способ 2)
console.error("2 Задание 2 способ")
let a = (42 / 7)
console.log("значение 1 выражения")
console.log(a)
let b = (2**4)
console.log("значение 2 выражения")
console.log(b)
let c = (100%4)
console.log("значение 3 выражения")
console.log(c)
console.log("Сумма всех 3х выражения")
console.log(a+b+c)

//3 задача
console.error("3 Задание")
console.log(2**4 + 2/3)
console.log("Ты просто супер! Правда!")